version: '2'
services:
 
 wp_samid:
  container_name: wp_samid
  build : ./wp/
  restart: unless-stopped
  environment:
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_PASSWORD: diemas040492
   WORDPRESS_DB_NAME: samid
  ports: 
   - "127.0.0.1:8085:80"
   - "127.0.0.1:8086:443" #buka port ini jika ini menggunakan https
  links:
   - db_samid:mysql
  volumes:
   - samid_volume:/var/www/html
 db_samid:
  container_name: db_samid
  build: ./db/
  restart: unless-stopped
  volumes:
   - samid_db_volume:/var/lib/mysql

volumes:
  samid_volume:
  samid_db_volume:

